### ISSUE TITLE
Rumors of no subtitles in .avi video mode, if true please fix.

### ISSUE THREAD

**Issue by gustarballs1983** [sfall-team/sfall#448]
as I'm in the process of remastering all classic fallout related videos, I stumbled on a chap from France who claims that subtitles aren't working when .avi videos are beeing displayed, could this be checked and taken care of?

**Comment by NovaRain** [comment]
While subtitles can barely show for the intro movie, they show OK for in-game ones (your HD videos in et tu):
![Intro](https://i.imgur.com/zkT362i.jpg)
![Ovrintro](https://i.imgur.com/RztN6B7.jpg)

**Comment by gustarballs1983** [comment]
what settings are You using?
I don't have subs under that video in et tu, or more importantly where did you put those videos i've put them in data\art\cuts, while the original vids are  in mods\fo1_base folder, i run in full hd graphics mode Mash's HRP =2 non-windowed graphics mode sfall =4....

**Comment by NovaRain** [comment]
Same in `data\art\cuts\`, I see subs in all sfall DX9 modes, but seems only when there are both intro.avi and ovrintro.avi.

**Comment by gustarballs1983** [comment]
Damn I must be missing something here..
I tried running with sfall's built in hrp tried disabling dx9 in f2_res.ini copied all contents of "cuts" catalogie that were extracted by undatUI.exe and still nothing? am i missing something here? where are the subtitle files placed anyways? it would seem undatUI.exe doen't extract them..
Could You help me on this?

**Comment by NovaRain** [comment]
I play the game in 1280x720 or 1280x960, the subs and videos play with both Mash's and sfall's built-in HRP.
Since AVI playback requires sfall's DX9 modes, the graphics mode setting in f2_res.ini has no real impact when you set the mode in ddraw.ini.
As for non-English:
![Ovrintro](https://i.imgur.com/AlphUvh.jpg)

I really have no idea what causes your problems because things work normal on my two different PCs. One is just an office desktop using Intel integrated graphics, another is my main rig using NVIDIA graphics. The only "special" thing I did to my et tu installation is to move all `fo1_base` files to data for using the mapper and other older tools, but that shouldn't really affect anything here.

**Comment by gustarballs1983** [comment]
Damn I don't know how but it suddenly started working!!
first i thought it was a matter of too long path in folder naming so i moved the whole to a folder that is more close to drive letter and made sure the folder names are 8 characters long max without any spaces, still nothing.. then i switched to 1280x960 in both ddraw.ini and in f2_res.ini and additionally set the f2_res.ini to play the movies in original size, and it displayed the subtities on the bottom line leaving lots of emoty space, next i set movie to strech =1 it worked too, and finally i changed the resolution to 1920x1080 and it's now working WTF??!! is there some sort of AI controlling Sfall??
