### ISSUE TITLE
3.x & 4.x difference

### ISSUE THREAD

**Issue by Paelor** [sfall-team/sfall#451]
Could you update the GitHub page so it explains the difference between the 3.x and 4.x downloads? It is not mentioned anywhere and it is confusing. Thanks!

**Comment by NovaRain** [comment]
There's practically no need to use older 3.8.x if you're using 4.x already, as it's just a trimmed down version of 4.x at best.
The main reason it's still being updated other than bug fixes is just I want to run newer content on Win2000 system natively.

**Comment by burner1024** [comment]
I think sfall could benefit from more documentation in general.
Scripting is well documented, and ddraw.ini is annotated, but other than that it's pretty lacking.

Just now by pure chance I learned that there's a `combat_is_over_p_proc` that's been reimplemented. How much of the stuff goes unused because no one knows about it?

How many bug fixes are there? Dozens? Hundreds? No list of these too. In fact, I don't even see a changelog in the repo.

Not saying it has to be tackled all at once, but it would be good to start building up the docs gradually.
