### ISSUE TITLE
request - script function to 'restack' all weapons in inven

### ISSUE THREAD

**Issue by nirran** [sfall-team/sfall#455]
as title says

i have a script that unloada ll weapons in dude inven,but if inven has a stack of unloaded same weapons,engine does not stack them,it creates a new stack,nothing is lost but kinda buggs,can provide save to test if u ask,this script will unload on press 'h'
[autoloot.zip](https://github.com/sfall-team/sfall/files/10506469/autoloot.zip)

asking for scripting command to restack items in inven

**Comment by NovaRain** [comment]
I think you can check the total copies of the unloaded weapon in player's inventory, remove all old copies, create a new weapon object and set its ammo count to 0 (since the weapon is "unloaded"), and re-add the same amount of weapons back to the inventory. It should be a single stack of the empty weapon.

**Comment by nirran** [comment]
ok ill try thnx
