### ISSUE TITLE
No way to get unarmed attack damage

### ISSUE THREAD

**Issue by phobos2077** [sfall-team/sfall#465]
Unless I'm missing something, there doesn't seem to be any way to get the actual unarmed damage values. These would be useful for re-implementing damage calculation in script (COMBATDAMAGE with full re-calculation of results).
Now it seems the only was is to hook into ITEMDAMAGE and store the argument values into variable.

**Comment by NovaRain** [comment]
> hook into ITEMDAMAGE and store the argument values into variable.

I don't see what's wrong with it. Since there's no "proto" for unarmed attack as weapons (so one can get min/max damage values from proto offsets), ITEMDAMAGE hook is an obvious choice. [gl_compute_damage](https://github.com/sfall-team/sfall/blob/master/artifacts/example_mods/ComputeDamage/gl_compute_damage.ssl) has a good example for this.

**Comment by phobos2077** [comment]
Well you still can't get the original unarmed damage values, if you want. But I guess you can work around it buy checking sfall INI files with get_ini opcodes and falling back to known defaults, since they are hard-coded and static.
