### ISSUE TITLE
Autoplay not triggering

### ISSUE THREAD

**Issue by blackpaulillyria** [sfall-team/sfall#573]
I am using sfall 4.4.5 and I only recently noticed that autoplay when idling inside the main menu doesn't trigger anymore. Instead, the intro video plays. Is there any particular reason for this change? I liked the autoplay option and used it to demo some cool locations.

**Comment by NovaRain** [comment]
It's been disabled since 4.3 in 2021. The recording mode is a leftover from old FO1 engine with very limited abilities. If you want to demonstrate Yesterday's content including dialogue or some other stuff, it may be easier to simply record actual gameplay as a video clip, unless you need to demo on an ancient potato PC that struggles with mpeg4 playback on a storefront.

**Comment by blackpaulillyria** [comment]
You're suggesting I record different demo clips, merge them or shuffle them if the player is idling in the main menu as a movie? I'm down for that if it's possible using a global script.

**Comment by NovaRain** [comment]
> You're suggesting I record different demo clips, merge them or shuffle them if the player is idling in the main menu as a movie? I'm down for that if it's possible using a global script.

No, I mean simply playing video clips in some media player.
